<?php

namespace RLMainBundle\Repository;

/**
 * JuristeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuristeRepository extends \Doctrine\ORM\EntityRepository
{
}
