<?php

namespace RLMainBundle\Repository;

/**
 * RecommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
